### ISSUE TITLE
[feature] tap the lock to execute facial rec. again

### ISSUE THREAD

**Issue by michaelrw10** [CPDigitalDarkroom/FastUnlockX#2]
sometimes you go to unlock the phone but the lock icon just jiggles, indicating a failed attempt. in order to unlock, you now have to either select 'cancel' and then swipe up again to initiate facial rec.  ..  or you have to move the phone down away from your face and then pull it up again, so it thinks youre trying to open your phone again, initiating the facial rec.

It would be nice if we could just tap the lock icon to initiate another round of facial rec

**Comment by jcarlosperez** [comment]
Closing as it now has auto retry feature
