### ISSUE TITLE
Missing header when trying to compile

### ISSUE THREAD

**Issue by yur1xpp** [CPDigitalDarkroom/FastUnlockX#4]
Hey, I'm trying to compile this, however it seems like the `Preferences.h`[here](https://github.com/CPDigitalDarkroom/FastUnlockX/blob/008a2615e1c773a153609c8feabb52ea392fcd96/Preferences/CPDDFUXRootListController.mm#L14) is missing. Did you missed it? Thanks in advance.

**Comment by CPDigitalDarkroom** [comment]
That's my bad, I added a file to use as a quick one-liner in my projects when importing preferences. I need to go back to these projects with a fresh theos installation and fix it so it compiles based on that. 

To compile, you'll need to replace that line with imports to any needed preference classes. I know for sure PSListController, maybe PSSpecifier as well.

**Comment by yur1xpp** [comment]
Thank you, that did actually solved the issue. I'm curious, do you have any update to the code since published? I'm trying to learn this code with the most updated one if that's okay :)

**Comment by CPDigitalDarkroom** [comment]
@yur1xpp pushed the most up to date code.

**Comment by yur1xpp** [comment]
Thank you so much @CPDigitalDarkroom, really appreciate it!
